# Generated by Django 2.2.3 on 2019-08-10 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientmodel',
            options={'verbose_name': 'Intgredient'},
        ),
        migrations.AlterModelOptions(
            name='recipemodel',
            options={'verbose_name': 'Recipe'},
        ),
        migrations.AlterModelOptions(
            name='stepmodel',
            options={'verbose_name': 'Step'},
        ),
    ]
