# Generated by Django 2.2.3 on 2019-08-11 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190811_0722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientmodel',
            options={'verbose_name': 'Ingredient'},
        ),
    ]
